### ISSUE TITLE
Network specification files do not parse tabs

### ISSUE THREAD

**Issue by breecummins** [shaunharker/DSGRN#18]
The network specification file below could not be read and claimed that variable PF3D7_0613800 was not valid:

`PF3D7_1146600 : (PF3D7_0613800)    : E`
`PF3D7_0611200 : (~PF3D7_1146600) : E`
`PF3D7_1308100 : (~PF3D7_1146600) : E`
`PF3D7_1305200 : (~PF3D7_1146600)(PF3D7_0611200)    : E`
`PF3D7_0613800 : PF3D7_1356900 + PF3D7_1308100 + PF3D7_1305200 : E`
`PF3D7_1356900 : PF3D7_0611200 : E`

I removed the tabs and then everything worked fine. However, it seems natural that someone might tab on either side of the colon for readability. Would it be easy to parse tabs, or should we just specify that no tabs are allowed in the network spec?

Edit: The tabs vanish on formatting. There is a tab before the second colon in the first and fourth lines.

**Comment by shaunharker** [comment]
It should work now for the dsgrn and Signatures programs. I haven't checked the hillmodel.py parser in the numerical simulations yet.
