### ISSUE TITLE
Incomplete output for dsgrn domaingraph

### ISSUE THREAD

**Issue by breecummins** [shaunharker/DSGRN#5]
The command 

`dsgrn network NETWORK domaingraph` 

does not return the complete set of cells for the network

I am working with the network networks/5D_2015_09_11.txt. In this network, x1 and x5 have two thresholds, x2 and x3 have one threshold, and x4 has three thresholds. Therefore, the domain described by `[ [0,1], [0,1], [1,2], [3,4], [1,2] ]` should exist. I call

`dsgrn network networks/5D_2015_09_11.txt domaingraph`

and capture the json string in python as domaincells_jsonstr. I retrieve the list of cell locations using python's json parser:

`domaincells = json.loads(domaincells_jsonstr)['cells']`

Lastly I check for the existence of my desired cell: 

`print [[0,1],[0,1],[1,2],[3,4],[1,2]] in domaincells`

The answer is False. I also scanned through the command line output of dsgrn trying to find it and could not.  

Because of the missing cells, I am also concerned that we may not be generating the entire domain graph from

`dsgrn network NETWORK domaingraph json PARAMETER`

**Comment by shaunharker** [comment]
I am unable to reproduce this.  From the command line I type

``` bash
dsgrn network networks/5D_2015_09_11.txt domaingraph > data.json
```

followed by

``` bash
python -c 'import json; print [[0,1],[0,1],[1,2],[3,4],[1,2]] in  json.load(open("data.json"))["cells"]'
```

and obtain the output
`True`.

Can you provide more information: (1) the output of `dsgrn network networks/5D_2015_09_11.txt domaingraph` and (2) the python code used to create `domaincells_jsonstr`?

**Comment by breecummins** [comment]
Hi Shaun,

I replicate your behavior. I put the print statement in the wrong place in
my code. The issue is a non-issue.

Thanks,
Bree
